# Project Configuration
app:
  name: "Real Estate ML"
  version: "0.1.0"

# Data paths
data:
  raw_data_path: "data/raw/"
  processed_data_path: "data/processed/"
  sample_data_path: "data/sample/"

# Model configuration
model:
  model_path: "models/current/"
  target_column: "price"
  test_size: 0.2
  random_state: 42

# API configuration
api:
  host: "0.0.0.0"
  port: 5000

# AWS configuration
aws:
  region: "us-east-1"
  s3_bucket: "your-bucket-name"
